part of faros__package;

/// A [DeviceDescriptor] for a Movisens device used in a [StudyProtocol].
///
/// This device descriptor defined the basic configuration of the Movisens
/// device, including the BTLE MAC [address], the [sensorName], the [sensorLocation]
/// and the [weight], [height], [age], [gender] of the user using the device.
@JsonSerializable(fieldRename: FieldRename.none, includeIfNull: false)
class FarosDevice extends DeviceDescriptor {
  static const String DEVICE_TYPE =
      '${DeviceDescriptor.DEVICE_NAMESPACE}.FarosDevice';

  static const String DEFAULT_ROLENAME = 'faros';
  String address;

  /// The MAC address of the sensor.
  String sensorName;

  /// The user-friendly name of the sensor.
  String sensorLocation;

  /// Sensor placement on body
  int weight;

  /// Weight of the person wearing the Movisens device in kg.
  int height;

  /// Height of the person wearing the Movisens device in cm.
  int age;

  /// Age of the person wearing the Movisens device in years.
  String gender;

  /// Gender of the person wearing the Movisens device, male or female.

  /// Create a new [FarosDevice].
  ///
  /// Default user setting is a 25 year old male, height 178 cm high, weight
  /// 78 kg with the sensor place on the chest.
  FarosDevice({
    String? roleName,
    required this.address,
    required this.sensorName,
    this.sensorLocation = "chest",
    this.gender = "male",
    this.height = 178,
    this.weight = 78,
    this.age = 25,
  }) : super(
          roleName: roleName ?? DEFAULT_ROLENAME,
          isMasterDevice: false,
          supportedDataTypes: [FarosSamplingPackage.FAROS],
        );

  @override
  Function get fromJsonFunction => _$FarosDeviceFromJson;
  factory FarosDevice.fromJson(Map<String, dynamic> json) =>
      FromJsonFactory().fromJson(json) as FarosDevice;
  @override
  Map<String, dynamic> toJson() => _$FarosDeviceToJson(
      this); //will be autogenerated when i run build_runner command
}

//
//
//
//
//
//
//
//
//
//
//
/// A Movisens [DeviceManager].
class FarosDeviceManager extends DeviceManager {
  // the last known voltage level of the Movisens device
  int _batteryLevel = -1;
  String? _connectionStatus;
  // StreamSubscription<Map<String, dynamic>>? _subscription;
  StreamSubscription<Map<Object?, Object?>>? _ecgDataStreamSubscription;
  StreamSubscription<Map<Object?, Object?>>? _accDataStreamSubscription;

  @override
  FarosDevice get deviceDescriptor => super.deviceDescriptor as FarosDevice;

  /// The [Movisens] device handler.
  /// Only available after this device manger has been initialized via the
  /// [initialize] method.
  Faros? _faros;

  /// Movisens user data as specified in the [FarosDevice] device descriptor.
  /// Only available after this device manger has been initialized via the
  /// [initialize] method.
  Map<String, String>? userData;

  @override
  String get id => userData?['sensorAddress'] ?? FarosDevice.DEVICE_TYPE;

  String? get connectionStatus => _connectionStatus;

  @override
  Future<void> onInitialize(DeviceDescriptor descriptor) async {
    assert(descriptor is FarosDevice,
        '$runtimeType - can only be initialized with a MovisensDevice device descriptor');

    userData = <String, String>{
      'weight': deviceDescriptor.weight.toString(),
      'height': deviceDescriptor.height.toString(),
      'gender': deviceDescriptor.gender.toString(),
      'age': deviceDescriptor.age.toString(),
      'sensorLocation': deviceDescriptor.sensorLocation,
      'sensorAddress': deviceDescriptor.address,
      'sensorName': deviceDescriptor.sensorName,
    };
  }

  /// The latest read of the battery level of the Movisens device.

  @override
  Future<bool> canConnect() async => userData != null;

  @override
  Future<DeviceStatus> onConnect() async {
    try {
      // create and connect to the Movisens device
      _faros = Faros(deviceDescriptor.address);

      // listen for Movisens events
      _ecgDataStreamSubscription = _faros?.ecgStream?.listen((event) {
        debug('$runtimeType :: Faros ecg event : $event');

        if (event.containsKey("ConnectionStatus")) {
          _connectionStatus =
              jsonDecode(event["BatteryLevel"].toString())["BATTERY_LEVEL"]
                  .toString();

          // TODO - set the right connection status - can this be other than connected?
          status = DeviceStatus.connected;
        }
      });

      _accDataStreamSubscription = _faros?.accelerometerStream?.listen((event) {
        debug('$runtimeType :: Faros accelerometer event : $event');
      });
    } catch (error) {
      warning(
          "$runtimeType - could not connect to device of type '$type' - error: $error");
      return DeviceStatus.error;
    }

    return DeviceStatus.connecting;
  }

  @override
  Future<bool> onDisconnect() async {
    _ecgDataStreamSubscription?.cancel();
    _accDataStreamSubscription?.cancel();
    return true;
  }
}
